dist: xenial
language: python
python: 3.7
install:
- pip install .
script:
- python -m pytest tests/
deploy:
  provider: pypi
  user: witlox
  password:
    secure: JzkfXAElg8dlbo+1IJMjcu+MMMXDOV+gfv1kpMhLq5cnau6lhokxfJVB7biYo9D2JMvEpTeS8m8trrztcjOvKOf5XmI7b5yitnK4+p0kWQdED10O5ois0Euscr3G7yfIdrlZtajlr6SAt/tRmQWdatpF7stHmDBu5vsJ0VFx0C232+kJFpzMFLd5ErkBEMPwV0E6Q91qGI5JBM8pO27K7NhHcetDlHjlm01EEQTUUz2JBHFAwU60a3Zfv3FVR4STwRiTe1sJyGa0qWi9qgwfeln8Yk7f/AX3ypn6KDgxlsbyqvhWmDlcAgIYuADmqCAE5V6p9Q3Tu+mtcBG4IH9E6G3shf7v8hcw3dQJN5wibqrnS6Ly34DroTg3KQR8kYA9eBxoqdjwyQwn+8FSzw+sGUsMLg1JXSepqsipWUzquB3Gr8RaabBsVvisAcziBELQ0klqOti1ZF4v1fgorfoQz0N0rOKIcwxXknfDKDP6fLK40I/yuCCvQfP8CBAjflGh/yNDg1cJwfGN4IsTGXHFFoALDPv0LNsWTpXHQOC1IUfhBDc6WxAi7RFTyjtbLI2+0KpHTkbv3iRGAj2i/ruGePnpVNwbHjeTc6JKcOkseEi6ffUtUxs2+FEndihtMJhK9f1E6M7ENnCTZBX3NVUH3qgSGpouUXBm/fxOA3zP/f0=
  skip_existing: true